import RevenueAnalytics from "../components/RevenueAnalytics";
import { Token, AIAgent } from "../types";
import { DollarSign } from "lucide-react";

interface RevenueAnalyticsPageProps {
  userTokens: Token[];
  userAgents: AIAgent[];
  referralCode?: string;
  aglTokenBalance?: number;
  showToast?: (message: string, type: "success" | "error" | "info") => void;
}

export default function RevenueAnalyticsPage({
  userTokens,
  userAgents,
  referralCode = "your-ref-code",
  aglTokenBalance = 0,
  showToast
}: RevenueAnalyticsPageProps) {

  const handleCopyReferralLink = () => {
    const link = `https://agl-studio.io/?ref=${referralCode}`;
    navigator.clipboard.writeText(link).then(() => {
      showToast?.("Referral link copied to clipboard!", "success");
    }).catch(() => {
      showToast?.("Failed to copy link", "error");
    });
  };

  const totalCreatorFees = userTokens.reduce((sum, t) => sum + t.creatorFeesEarned, 0);

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Page Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold font-display tracking-tight text-white">Revenue & Referral Analytics</h1>
          <p className="text-xs text-zinc-400 mt-1">Track earnings, referral payouts, and commission history</p>
        </div>
      </div>

      {/* Main Analytics Component */}
      <RevenueAnalytics
        userTokens={userTokens}
        userAgents={userAgents}
        referralCode={referralCode}
        totalCreatorFeesEarned={totalCreatorFees}
        aglTokenBalance={aglTokenBalance}
        onCopyReferralLink={handleCopyReferralLink}
      />

      {/* Revenue Optimization Tips */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="glass-panel p-4 rounded-xl border border-white/5 bg-brand-purple/5">
          <h4 className="text-xs font-bold text-brand-purple uppercase mb-2">Maximize Creator Fees</h4>
          <p className="text-[10px] text-zinc-300 leading-relaxed">
            Deploy popular token projects and NFT collections to generate consistent creator fees. Each 1% of trading volume contributes directly to your earnings.
          </p>
        </div>
        <div className="glass-panel p-4 rounded-xl border border-white/5 bg-cyan-500/5">
          <h4 className="text-xs font-bold text-cyan-400 uppercase mb-2">Grow Agent Revenue</h4>
          <p className="text-[10px] text-zinc-300 leading-relaxed">
            Deploy profitable AI agents with useful capabilities. Higher query fees and usage rates multiply your passive income streams significantly.
          </p>
        </div>
        <div className="glass-panel p-4 rounded-xl border border-white/5 bg-emerald-500/5">
          <h4 className="text-xs font-bold text-emerald-400 uppercase mb-2">Referral Strategy</h4>
          <p className="text-[10px] text-zinc-300 leading-relaxed">
            Share your referral link to earn 20% of all fees from referred users. Build community and scale earnings passively through network effects.
          </p>
        </div>
        <div className="glass-panel p-4 rounded-xl border border-white/5 bg-yellow-500/5">
          <h4 className="text-xs font-bold text-yellow-400 uppercase mb-2">Claim & Reinvest</h4>
          <p className="text-[10px] text-zinc-300 leading-relaxed">
            Regularly claim your ETH and AGL rewards. Reinvest earnings into new projects or lock them in high-yield staking vaults for compound growth.
          </p>
        </div>
      </div>

      {/* Revenue FAQ */}
      <div className="glass-panel p-6 rounded-2xl border border-white/5 bg-zinc-900/10 space-y-4">
        <h3 className="text-xs font-bold font-display uppercase tracking-wider text-white flex items-center gap-1.5">
          <DollarSign className="w-4 h-4 text-emerald-400" />
          Revenue Questions
        </h3>
        <div className="space-y-4">
          <div>
            <p className="text-xs font-bold text-white mb-1">How are creator fees calculated?</p>
            <p className="text-[10px] text-zinc-300">Every trade on bonding curves incurs a 1% fee. As a creator, you receive 100% of this fee for tokens you deployed. Fees are automatically credited to your account.</p>
          </div>
          <div>
            <p className="text-xs font-bold text-white mb-1">What's the referral commission structure?</p>
            <p className="text-[10px] text-zinc-300">Referrers earn 20% of all fees generated by users they invite. This includes creator fees, agent usage fees, and trading commissions. Rewards are paid in ETH or AGL tokens.</p>
          </div>
          <div>
            <p className="text-xs font-bold text-white mb-1">When can I claim my earnings?</p>
            <p className="text-[10px] text-zinc-300">Earnings are calculated in real-time and can be claimed immediately through the Payout dashboard. Gas fees are sponsored for AA wallets on Base Sepolia.</p>
          </div>
          <div>
            <p className="text-xs font-bold text-white mb-1">How do agent revenues work?</p>
            <p className="text-[10px] text-zinc-300">When you deploy an AI agent with a usage fee, each query transaction generates revenue for you. The more queries your agent processes, the more you earn passively.</p>
          </div>
        </div>
      </div>
    </div>
  );
}
